### PR TITLE
IMPORT JQUERY TO WEBPAGES ON DEMAND

### PR DESCRIPTION
**Pull request by dhruvramani**
Completed code for the task : IMPORT JQUERY TO WEBPAGES ON DEMAND

### CODE REVIEW

**Comment by ty221** [comment]
Hello, thank you for pushing your code there! Your PR looks ok, however please add your code to separate directory (you need to create one) :D 

Thanks!

**Comment by tradzik** [comment]
Hmmm... @mariobehling has renamed this repository and now it seems adding your files to is not good idea (off-topic). @mariobehling Can you tell me what should we do with this PR?

**Comment by mariobehling** [comment]
Not sure, as another mentor took care. Please relay question to devs. Just renamed the project for clarification.

**Comment by tradzik** [comment]
@mariobehling  I checked Google Melange and this is task of @andunslg . Maybe he can help us in this case...

**Pull request closed without merging**
