### PR TITLE
The jury is updated

### PR DESCRIPTION
**Pull request by agarwalaman263**
#8 is resolved

### CODE REVIEW

**Comment by mariobehling** [comment]
Please download the photo from the other repos in the same quality.

**Comment by mariobehling** [comment]
You are changing a lot of lines without need.

**Comment by agarwalaman263** [comment]
As the elegant icons were not having the GitHub icon so I have replaced them with font awesome icons. As the icons are used in various places so there are more modifications getting reflected

**Comment by mariobehling** [comment]
This is not part of the issue. Please ensure you stick to best practices to make it easy for reviewers. Change one thing at a time.

Implement the Github icons in another issue/PR and follow the example of fossasia.org.

Please provide screenshots and test pages for your PRs.

**Pull request closed without merging**
